### ISSUE TITLE
В Python няма `switch-case`

### ISSUE THREAD

**Issue by Alaxe** [SoftUni/Programming-Basics-Book-Python-BG#28]
## Линк към файла
[chapter-00-preface.md](https://github.com/SoftUni/Programming-Basics-Book-Python-BG/blob/master/chapter-00-preface.md)

## Описание
В предговора е написано, че една от условните конструкции в Python е `switch-case`. В Python няма такава конструкция ([oфициална документация](https://docs.python.org/3/tutorial/controlflow.html#if-statements)).
## Текущ текст
..., използване на условни конструкции (`if`, `if-else`, `switch-case`), ...
## Текст след поправката
..., използване на условни конструкции (`if`, `if-else`, `if-elif-else`), ...

**Comment by nakov** [comment]
Оправено, беше бъг по наследство от старата книга за C#.
