### ISSUE TITLE
Форматиран изход -> петте начина

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-Python-BG#6]
## Линк към файла

https://github.com/SoftUni/Programming-Basics-Book-Python-BG/blob/master/chapter-02-simple-calculations.md

## Описание

В глава "Глава 2.1. Прости пресмятания с числа" да се добавят и обяснят петте основни начина за печатане на форматиран текст в Python:

Изброяване със запетайки:
```python
width = 5
height = 7
print("width =", width, "; height =", height, "; area =", width * height)
```

Съединение на текст с оператора `+`:
```python
width = 5
height = 7
print("width = " + str(width) + "; height = " + str(height) + "; area = " + str(width * height))
```

С форматиращи идентификaтори `%d`, `%s`, `%f`:
```python
width = 5
height = 7
text = "area"
print("width = %d; height = %d; %s = %d" % (width, height, text, width * height))
```
В примера `%d` обозначава цяло число, а `%s` обозначава стринг (текстова стойност).

Чрез функцията .format(...) за форматиране на текст по шаблон:
```python
width = 5
height = 7
print("width = {}; height = {}; area = {}".format(width, height, width * height))
```

Чрез форматиращ низ `f"..."`:
```python
width = 5
height = 7
print(f"width = {width}; height = {height}; area = {width * height}")
```
Това е **препоръчителният начин** за печатане на форматиран текст, защото е най-кратък и най-лесно разбираем, съответно и кодът се чете най-лесно.

Важно е да се покажат всичките начини, защото по-късно ще се използва всеки от тях според ситуацията и според автора на съответния код. Всичките са валидни. Последният като че ли е най-лесен, най-кратък и е за препоръчване.

**Comment by miglen** [comment]
Благодаря за подсещането.

**Comment by bsdemon** [comment]
Това е правилния начин за форматиране:
https://docs.python.org/3.6/library/string.html#format-examples

**Comment by miglen** [comment]
В крайна сметка осъзнах, че ще ползвам .format в моя случай, тъй като има повторение на използваните променливи или изрази.

**Comment by nakov** [comment]
Fixed. The 5 ways to format text in Python are now in the book text.
